"""
Build script for Eye Tracker macOS app bundle.
Creates a standalone .app using PyInstaller with the same behavior as the Windows EXE build.
"""

import os
import platform
import shutil
import subprocess
import sys
import urllib.request


APP_NAME = "EyeTracker"
MODEL_URL = "https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task"


def project_root() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def download_model() -> str:
    """Download the face landmarker model if not present."""
    model_dir = os.path.join(project_root(), "models")
    model_path = os.path.join(model_dir, "face_landmarker.task")

    if os.path.exists(model_path):
        print(f"Model already exists at {model_path}")
        return model_path

    os.makedirs(model_dir, exist_ok=True)
    print("Downloading face landmarker model...")
    urllib.request.urlretrieve(MODEL_URL, model_path)
    print(f"Model downloaded to {model_path}")
    return model_path


def clean_build() -> None:
    """Remove previous build artifacts."""
    root = project_root()
    for folder in ["build", "dist"]:
        path = os.path.join(root, folder)
        if os.path.exists(path):
            print(f"Cleaning {path}...")
            shutil.rmtree(path)


def ensure_required_files() -> None:
    """Fail fast with clear messages if critical files are missing."""
    root = project_root()
    required_files = [
        "launcher.py",
        "app.py",
        "main.py",
        "gaze_estimator.py",
        "logger.py",
        "requirements.txt",
        "aoi_config_per_image.json",
    ]
    required_dirs = ["templates", "static", "images"]

    missing_files = [f for f in required_files if not os.path.exists(os.path.join(root, f))]
    missing_dirs = [d for d in required_dirs if not os.path.isdir(os.path.join(root, d))]

    if missing_files or missing_dirs:
        if missing_files:
            print("Missing required files:")
            for f in missing_files:
                print(f"  - {f}")
        if missing_dirs:
            print("Missing required directories:")
            for d in missing_dirs:
                print(f"  - {d}/")
        sys.exit(1)


def run_pyinstaller() -> None:
    """Build a macOS .app bundle using PyInstaller."""
    root = project_root()

    sep = ":"  # macOS path separator for --add-data
    add_data = [
        f"templates{sep}templates",
        f"static{sep}static",
        f"images{sep}images",
        f"models{sep}models",
        f"aoi_config_per_image.json{sep}.",
    ]

    if os.path.exists(os.path.join(root, "aoi_config.json")):
        add_data.append(f"aoi_config.json{sep}.")

    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "launcher.py",
        "--name",
        APP_NAME,
        "--windowed",  # Build app bundle without terminal window
        "--onedir",    # Keep same behavior style as Windows folder distribution
        "--noconfirm",
        "--clean",
        "--collect-all",
        "mediapipe",
        "--collect-data",
        "cv2",
        "--hidden-import",
        "mediapipe.tasks.python.vision.face_landmarker",
        "--hidden-import",
        "mediapipe.python._framework_bindings",
        "--hidden-import",
        "flask",
        "--hidden-import",
        "jinja2",
        "--hidden-import",
        "werkzeug",
    ]

    for data_item in add_data:
        cmd.extend(["--add-data", data_item])

    print("Running PyInstaller...")
    print(" ".join(cmd))
    subprocess.check_call(cmd, cwd=root)


def print_success() -> None:
    root = project_root()
    app_path = os.path.join(root, "dist", f"{APP_NAME}.app")

    print("\n" + "=" * 70)
    print("MAC BUILD COMPLETE")
    print("=" * 70)
    print(f"App bundle: {app_path}")
    print("\nHow to run:")
    print(f"  1) Finder: open dist/{APP_NAME}.app")
    print(f"  2) Terminal: open \"{app_path}\"")
    print("\nNotes:")
    print("  - Keep images in images/pre and images/post.")
    print("  - Output CSV logs are generated by the app exactly like the Windows build.")
    print("  - First run may require macOS permissions for Camera access.")
    print("=" * 70)


def build() -> None:
    root = project_root()
    os.chdir(root)

    if platform.system() != "Darwin":
        print("Error: build_app_mac.py must be run on macOS.")
        print("Current platform:", platform.system())
        sys.exit(1)

    ensure_required_files()

    print("Installing/updating dependencies...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"], cwd=root)

    print("\nEnsuring model is available...")
    download_model()

    print("\nCleaning previous builds...")
    clean_build()

    print("\nBuilding macOS app bundle...")
    run_pyinstaller()

    print_success()


if __name__ == "__main__":
    build()
